<?php

namespace ContainerIh461Mf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I4PXUiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i4_pXUi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i4_pXUi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'uvdesk' => ['services', 'uvdesk.service', 'getUvdesk_ServiceService', false],
        ], [
            'container' => '?',
            'uvdesk' => '?',
        ]);
    }
}
