<?php

namespace ContainerIh461Mf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_9J4O58aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.9J4O58a' shared service.
     *
     * @return \Webkul\UVDesk\ApiBundle\API\UserPasswordEncoderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "Webkul\\UVDesk\\ApiBundle\\API\\Customers::updateCustomerRecord()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Webkul\\UVDesk\\ApiBundle\\API\\UserPasswordEncoderInterface". Did you forget to add a use statement?');
    }
}
