<?php

namespace ContainerIh461Mf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2jqOiLnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2jqOiLn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2jqOiLn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'fileSystem' => ['services', 'uvdesk.core.file_system.service', 'getUvdesk_Core_FileSystem_ServiceService', false],
            'passwordEncoder' => ['privates', '.errored.9J4O58a', NULL, 'Cannot determine controller argument for "Webkul\\UVDesk\\ApiBundle\\API\\Customers::updateCustomerRecord()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Webkul\\UVDesk\\ApiBundle\\API\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
        ], [
            'container' => '?',
            'eventDispatcher' => '?',
            'fileSystem' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
