<?php

namespace ContainerIh461Mf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnouncementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\SupportCenterBundle\Controller\Announcement' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Controller\Announcement
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/support-center-bundle/Controller/Announcement.php';

        $container->services['Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Announcement'] = $instance = new \Webkul\UVDesk\SupportCenterBundle\Controller\Announcement(($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['user.service'] ?? $container->getUser_ServiceService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Announcement', $container));

        return $instance;
    }
}
