version: "3.8"

services:
  web:
    image: stableuvdesk
    ports:
      - "8888:80"
    environment:
      WEB_DB_HOST: database
      WEB_DB_USER: root
      WEB_DB_PASSWORD: "root"
      WEB_DB_NAME: uvdesk
    depends_on:
      - database
    networks:
      my_net:
        ipv4_address: "192.168.1.3"
  
  
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uvdesk
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      my_net:
        ipv4_address: "192.168.1.4"

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/27"