services:
  web:
    image: stableuvdesk
    ports:
      - "8888:80"
    environment:
      WEB_DB_HOST: database
      WEB_DB_USER: root
      WEB_DB_PASSWORD: "root"
      WEB_DB_NAME: uvdesk
    networks:
      virtnet:
        ipv4_address: 192.167.1.3
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uvdesk
    ports:
      - "3306:3306"
    volumes:
      - mysqlyvdesk:/var/lib/mysql
    networks:
      virtnet:
        ipv4_address: 192.167.1.4

volumes:
  mysqlyvdesk:
    external: false

networks:
  virtnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.1.0/27
          gateway: 192.167.1.1