apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deploy
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: maksfed31/uvdeskbeta:latest
        ports: 
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: 80
    targetPort: 80
  type: NodePort