<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDbHL46\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDbHL46/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDbHL46.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDbHL46\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVDbHL46\App_KernelDevDebugContainer([
    'container.build_hash' => 'VDbHL46',
    'container.build_id' => 'ee0a86bd',
    'container.build_time' => 1746774066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDbHL46');
