name: Deploy artifact to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring

      - name: Create zip archive
        run: |
          zip -r app.zip . -x ".git/*" ".github/*"

      - name: Move zip to temp dir
        run: |
          mkdir upload
          mv app.zip upload/

      - name: Upload zip to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "php-bucket-storage"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'upload'
          DEST_DIR: 'deployments'
